/**
 * Cross-language conformance: the JS runtime must agree with the Python contracts.
 *
 * conformance-corpus.json carries, for every case, the verdict the Python
 * contracts ACTUALLY produced (generated by running them, never hand-written).
 * This replays all of them through the JS port. Any mismatch means the two
 * implementations have drifted, and the JS side -- the one that actually runs in
 * production -- is not enforcing the plan.
 *
 * Four layers, four owners on this side:
 *   structure -> ajv against op-manifest.schema.json  (the schema is NOT rewritten
 *                in JS; a second copy would drift immediately)
 *   semantic  -> lib/op-semantics.js
 *   pairing   -> lib/op-resolution.js validateResolutionAgainstTarget
 *   cas       -> lib/op-resolution.js checkResolutionCas
 *
 * Run: node --test scripts/schema/conformance.test.mjs
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';

import { validateSemantics } from '../../lib/op-semantics.js';
import { validateResolutionAgainstTarget, checkResolutionCas } from '../../lib/op-resolution.js';

const here = dirname(fileURLToPath(import.meta.url));
const corpus = JSON.parse(readFileSync(join(here, 'conformance-corpus.json'), 'utf8'));
const schema = JSON.parse(readFileSync(join(here, 'op-manifest.schema.json'), 'utf8'));

const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);
const validateStructure = ajv.compile(schema);

/** Run one case through the layer that owns it and return a comparable verdict. */
function verdict(c) {
  switch (c.layer) {
    case 'structure': {
      const valid = validateStructure(c.input.manifest);
      return { valid };
    }
    case 'semantic': {
      const errs = validateSemantics(c.input.manifest);
      return { valid: errs.length === 0, errorCount: errs.length, errs };
    }
    case 'pairing': {
      const errs = validateResolutionAgainstTarget(c.input.resolution, c.input.original);
      return { valid: errs.length === 0, errorCount: errs.length, errs };
    }
    case 'cas': {
      const r = checkResolutionCas(c.input.original, c.input.resolutionOpId);
      return { ok: r.ok, code: r.code };
    }
    default:
      throw new Error(`unknown layer ${c.layer}`);
  }
}

test('corpus is well-formed and covers every layer', () => {
  assert.equal(corpus.cases.length, corpus.caseCount,
    'caseCount must match the actual number of cases');
  const layers = new Set(corpus.cases.map((c) => c.layer));
  for (const want of ['structure', 'semantic', 'pairing', 'cas']) {
    assert.ok(layers.has(want), `corpus must exercise the ${want} layer`);
  }
  const negatives = corpus.cases.filter((c) => c.legality === 'intentionally-illegal');
  assert.ok(negatives.length >= corpus.cases.length / 3,
    'a corpus that is mostly positives proves little');
});

// GATE: every manifest the corpus declares legal must pass structure AND semantic
// checks here too. Without this, a fixture that is illegal in a way the case does
// not test would still count as "matched" -- the background-object false-green
// that a whole revision was lost to.
test('must-be-legal fixtures really are legal on the JS side', () => {
  for (const c of corpus.cases.filter((x) => x.legality === 'must-be-legal')) {
    for (const key of ['manifest', 'original', 'resolution']) {
      const obj = c.input[key];
      if (!obj) continue;
      assert.ok(validateStructure(obj),
        `${c.id}: input.${key} must satisfy the schema, got `
        + JSON.stringify(validateStructure.errors?.slice(0, 2)));
      const errs = validateSemantics(obj);
      assert.equal(errs.length, 0, `${c.id}: input.${key} must be semantically clean, got ${errs[0]}`);
    }
  }
});

for (const c of corpus.cases) {
  test(`${c.layer}/${c.id.split('/').slice(1).join('/')} [${c.legality}]`, () => {
    const got = verdict(c);
    for (const [key, want] of Object.entries(c.expect)) {
      assert.equal(got[key], want,
        `${c.id}: expected ${key}=${JSON.stringify(want)}, got ${JSON.stringify(got[key])}`
        + (got.errs ? `\n  JS errors: ${JSON.stringify(got.errs.slice(0, 3), null, 2)}` : ''));
    }
  });
}
