import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';import{join}from'node:path';import{tmpdir}from'node:os';
import{ProposalStore,resolveSkillProposalMode,needsSkillProposal,canonicalSkillHashes}from'../../lib/skill-proposals.js';import{applySkillMutation}from'../../lib/skill-mutation.js';import{writeCrystallizedSkill}from'../../lib/skills.js';
const O='a'.repeat(32);const rec=n=>[{id:`m_${n}`,kind:'lesson',importance:2,content:n,tags:[n]}];
function env(){const root=mkdtempSync(join(tmpdir(),'prop-')),skillsDir=join(root,'skills');mkdirSync(skillsDir,{recursive:true});return{root,skillsDir,archiveDir:join(root,'arc'),store:new ProposalStore({workspaceDir:root,skillsDir,ownerId:O})}}
function create(e,n='alpha'){return writeCrystallizedSkill(e.skillsDir,n,n,rec(n),{warn(){}},`# ${n}\nbody`,undefined,{ownerId:O})}

test('resolver freezes balanced as proposal-first and autonomous receipt rules',()=>{assert.equal(resolveSkillProposalMode({skillProposalMode:'inherit',approvalMode:'balanced'}),'balanced');assert.equal(resolveSkillProposalMode({skillProposalMode:'autonomous',approvalMode:'manual'}),'autonomous');for(const a of['crystallize','refine','fold','converge'])assert.equal(needsSkillProposal(a,{approvalMode:'balanced'}),true);assert.equal(needsSkillProposal('crystallize',{approvalMode:'autonomous'}),false);assert.equal(needsSkillProposal('refine',{approvalMode:'autonomous'},false),true);assert.equal(needsSkillProposal('refine',{approvalMode:'autonomous'},true),false);assert.equal(needsSkillProposal('rollback',{approvalMode:'autonomous'},true),true)});
test('proposal publishes two complete files atomically and lists it',()=>{const e=env();try{const p=e.store.create({action:'crystallize',targetSkill:'a',body:'# A',sourceIds:['m1']});assert.ok(existsSync(join(e.root,'skill-proposals',p.id,'PROPOSAL.md')));assert.ok(existsSync(join(e.root,'skill-proposals',p.id,'meta.json')));assert.equal(e.store.list()[0].proposalHash.length,64)}finally{rmSync(e.root,{recursive:true,force:true})}});
test('content and semantic state hashes are independent',()=>{const a='---\nname: x\n---\n# X\nbody\n<!--dsh-evolve-state:{"tag":"x","version":"1"}-->';const b=a.replace('body','edited');const c=a.replace('"1"','"2"');assert.notEqual(canonicalSkillHashes(a).contentHash,canonicalSkillHashes(b).contentHash);assert.equal(canonicalSkillHashes(a).stateHash,canonicalSkillHashes(b).stateHash);assert.equal(canonicalSkillHashes(a).contentHash,canonicalSkillHashes(c).contentHash);assert.notEqual(canonicalSkillHashes(a).stateHash,canonicalSkillHashes(c).stateHash)});
test('manual edit after proposal makes apply stale with zero write',()=>{const e=env();try{create(e);const p=e.store.create({action:'fold',targetSkill:'alpha',body:'# replacement'});const file=join(e.skillsDir,'alpha','SKILL.md');writeFileSync(file,readFileSync(file,'utf8')+'\nHUMAN EDIT');const check=e.store.checkBase(e.store.read(p.id));assert.equal(check.ok,false);assert.match(readFileSync(file,'utf8'),/HUMAN EDIT/)}finally{rmSync(e.root,{recursive:true,force:true})}});
test('O_EXCL claim means a double apply has one executor',()=>{const e=env();try{const p=e.store.create({action:'crystallize',targetSkill:'a',body:'# A'});assert.equal(e.store.claim(p.id,'op1').status,'acquired');assert.equal(e.store.claim(p.id,'op2').status,'applying');assert.equal(e.store.finalize(p.id,'op2','applied',{}).ok,false);assert.equal(e.store.finalize(p.id,'op1','applied',{ok:true}).ok,true)}finally{rmSync(e.root,{recursive:true,force:true})}});

test('checkBase rejects a semantic-state-only edit',()=>{const e=env();try{create(e);const p=e.store.create({action:'fold',targetSkill:'alpha',body:'# replacement'});const file=join(e.skillsDir,'alpha','SKILL.md');const before=readFileSync(file,'utf8');writeFileSync(file,before.replace(/"version":"[^"]+"/, '"version":"9.9.9"'));const c=e.store.checkBase(e.store.read(p.id));assert.equal(c.ok,false,'state-only edit must be stale');assert.notEqual(c.expected.stateHash,c.got.stateHash)}finally{rmSync(e.root,{recursive:true,force:true})}});

test('claim file is O_EXCL and cannot be overwritten by a second claimant',()=>{const e=env();try{const p=e.store.create({action:'crystallize',targetSkill:'a',body:'# A'});e.store.claim(p.id,'op1');const claimFile=join(e.root,'skill-proposals',p.id,'.claim');const first=readFileSync(claimFile,'utf8');e.store.update(p.id,{state:'pending',opId:null});e.store.claim(p.id,'op2');assert.equal(readFileSync(claimFile,'utf8'),first);assert.match(first,/op1/);assert.doesNotMatch(first,/op2/)}finally{rmSync(e.root,{recursive:true,force:true})}});

test('size cap allows over-limit only when strictly shorter',()=>{const e=env();try{let r=applySkillMutation({action:'crystallize',source:'model-tool',skillsDir:e.skillsDir,archiveDir:e.archiveDir,ownerId:O,config:{skillMaxChars:1000},payload:{name:'big',tag:'x',records:[],body:'x'.repeat(1001)}});assert.equal(r.ok,false);create(e);const file=join(e.skillsDir,'alpha','SKILL.md');writeFileSync(file,readFileSync(file,'utf8')+'x'.repeat(1200));r=applySkillMutation({action:'fold',source:'model-tool',skillsDir:e.skillsDir,archiveDir:e.archiveDir,ownerId:O,config:{skillMaxChars:1000},payload:{name:'alpha',body:'x'.repeat(900)}});assert.equal(r.ok,true)}finally{rmSync(e.root,{recursive:true,force:true})}});
test('real Web surface has proposal list/apply/reject but no model apply tool',()=>{const web=readFileSync(new URL('../../lib/web-routes.js',import.meta.url),'utf8'),idx=readFileSync(new URL('../../lib/index.js',import.meta.url),'utf8');assert.match(web,/\/proposals\/`/);assert.match(web,/\['apply','reject'\]/);assert.equal(/name:\s*'skill_apply'/.test(idx),false);assert.equal(/name:\s*'skill_proposals'/.test(idx),false)});
